COMMENT ON TYPE "CommentStatus" IS '评论审核可见状态：PUBLISHED 正常显示，HIDDEN 隐藏，DELETED 删除。';
COMMENT ON TYPE "ResourceType" IS '可被评论或索引的资源类型：TRACK、ALBUM、POST。';
COMMENT ON TYPE "CreatorReleaseStatus" IS '发行工作流状态。';
COMMENT ON TYPE "ReleaseAccessModel" IS '发行访问模式：open 免费访问，purchase 购买访问。';
COMMENT ON TYPE "StorageNetwork" IS 'Pinata 文件网络可见性。';
COMMENT ON TYPE "PurchaseStatus" IS '购买交易确认状态。';
COMMENT ON TYPE "ReportStatus" IS '评论举报处理状态。';
COMMENT ON TYPE "ModerationAction" IS '评论审核动作。';

COMMENT ON TABLE "users" IS '应用用户。';
COMMENT ON COLUMN "users"."id" IS '应用内部用户 ID。';
COMMENT ON COLUMN "users"."displayName" IS '用户公开展示名称。';
COMMENT ON COLUMN "users"."avatarUrl" IS '用户头像地址。';
COMMENT ON COLUMN "users"."primaryWalletIdentityId" IS '当前主钱包身份 ID。';
COMMENT ON COLUMN "users"."createdAt" IS '创建时间。';
COMMENT ON COLUMN "users"."updatedAt" IS '更新时间。';

COMMENT ON TABLE "wallet_identities" IS '已验证钱包身份。';
COMMENT ON COLUMN "wallet_identities"."id" IS '钱包身份记录 ID。';
COMMENT ON COLUMN "wallet_identities"."userId" IS '归属用户 ID。';
COMMENT ON COLUMN "wallet_identities"."address" IS '钱包地址，保留校验和。';
COMMENT ON COLUMN "wallet_identities"."addressLower" IS '小写钱包地址，用于唯一约束查询。';
COMMENT ON COLUMN "wallet_identities"."chainId" IS '钱包所在链 ID。';
COMMENT ON COLUMN "wallet_identities"."verifiedAt" IS '首次验证时间。';
COMMENT ON COLUMN "wallet_identities"."lastAuthenticatedAt" IS '最近认证完成时间。';
COMMENT ON COLUMN "wallet_identities"."createdAt" IS '创建时间。';
COMMENT ON COLUMN "wallet_identities"."updatedAt" IS '更新时间。';

COMMENT ON TABLE "siwe_nonces" IS 'SIWE 一次性 nonce（仅存哈希）。';
COMMENT ON COLUMN "siwe_nonces"."id" IS 'nonce 记录 ID。';
COMMENT ON COLUMN "siwe_nonces"."nonceHash" IS 'nonce 的 SHA-256 哈希。';
COMMENT ON COLUMN "siwe_nonces"."requestedAddress" IS '申请 nonce 时指定的钱包地址。';
COMMENT ON COLUMN "siwe_nonces"."requestedAddressLower" IS '申请地址的小写形式。';
COMMENT ON COLUMN "siwe_nonces"."requestedChainId" IS '申请 nonce 时指定链 ID。';
COMMENT ON COLUMN "siwe_nonces"."expiresAt" IS '过期时间。';
COMMENT ON COLUMN "siwe_nonces"."consumedAt" IS '消费时间。';
COMMENT ON COLUMN "siwe_nonces"."createdAt" IS '创建时间。';

COMMENT ON TABLE "auth_sessions" IS 'SIWE 验签成功后的服务端会话。';
COMMENT ON COLUMN "auth_sessions"."id" IS '会话记录 ID。';
COMMENT ON COLUMN "auth_sessions"."userId" IS '用户 ID。';
COMMENT ON COLUMN "auth_sessions"."walletIdentityId" IS '创建会话的钱包身份 ID。';
COMMENT ON COLUMN "auth_sessions"."tokenHash" IS '会话令牌哈希。';
COMMENT ON COLUMN "auth_sessions"."address" IS '验签钱包地址。';
COMMENT ON COLUMN "auth_sessions"."chainId" IS '验签链 ID。';
COMMENT ON COLUMN "auth_sessions"."domain" IS 'SIWE domain。';
COMMENT ON COLUMN "auth_sessions"."uri" IS 'SIWE URI。';
COMMENT ON COLUMN "auth_sessions"."issuedAt" IS '消息签发时间。';
COMMENT ON COLUMN "auth_sessions"."verifiedAt" IS '服务端验签成功时间。';
COMMENT ON COLUMN "auth_sessions"."expiresAt" IS '会话过期时间。';
COMMENT ON COLUMN "auth_sessions"."lastSeenAt" IS '最近观察到活跃时间。';
COMMENT ON COLUMN "auth_sessions"."revokedAt" IS '撤销时间。';
COMMENT ON COLUMN "auth_sessions"."createdAt" IS '创建时间。';

COMMENT ON TABLE "storage_objects" IS 'IPFS 内容对象（CID 级）。';
COMMENT ON COLUMN "storage_objects"."id" IS '内容对象 ID。';
COMMENT ON COLUMN "storage_objects"."cid" IS 'IPFS CID。';
COMMENT ON COLUMN "storage_objects"."size" IS '内容大小（字节）。';
COMMENT ON COLUMN "storage_objects"."mimeType" IS '内容 MIME 类型。';
COMMENT ON COLUMN "storage_objects"."createdAt" IS '创建时间。';
COMMENT ON COLUMN "storage_objects"."updatedAt" IS '更新时间。';

COMMENT ON TABLE "storage_uploads" IS '第三方存储服务上的一次上传行为。';
COMMENT ON COLUMN "storage_uploads"."id" IS '上传记录 ID。';
COMMENT ON COLUMN "storage_uploads"."storageObjectId" IS '内容对象 ID。';
COMMENT ON COLUMN "storage_uploads"."uploaderUserId" IS '上传用户 ID。';
COMMENT ON COLUMN "storage_uploads"."pinataId" IS 'Pinata 文件 ID。';
COMMENT ON COLUMN "storage_uploads"."originalName" IS '上传原始文件名。';
COMMENT ON COLUMN "storage_uploads"."network" IS 'Pinata 网络可见性。';
COMMENT ON COLUMN "storage_uploads"."groupId" IS 'Pinata group ID。';
COMMENT ON COLUMN "storage_uploads"."createdAt" IS '创建时间。';

COMMENT ON TABLE "platform_contract_deployments" IS '平台在特定链上的一套合约部署。';
COMMENT ON COLUMN "platform_contract_deployments"."id" IS '部署记录 ID。';
COMMENT ON COLUMN "platform_contract_deployments"."chainId" IS '链 ID。';
COMMENT ON COLUMN "platform_contract_deployments"."chainName" IS '链名称。';
COMMENT ON COLUMN "platform_contract_deployments"."deploymentKey" IS '部署键（环境/版本）。';
COMMENT ON COLUMN "platform_contract_deployments"."isActive" IS '是否为当前活跃部署。';
COMMENT ON COLUMN "platform_contract_deployments"."musicAssetAddress" IS 'MusicAsset 合约地址。';
COMMENT ON COLUMN "platform_contract_deployments"."musicAssetAddressLower" IS 'MusicAsset 小写地址。';
COMMENT ON COLUMN "platform_contract_deployments"."royaltySplitterFactoryAddress" IS '版税分账工厂地址。';
COMMENT ON COLUMN "platform_contract_deployments"."royaltySplitterFactoryAddressLower" IS '版税分账工厂小写地址。';
COMMENT ON COLUMN "platform_contract_deployments"."platformHubAddress" IS '平台 Hub 地址。';
COMMENT ON COLUMN "platform_contract_deployments"."platformHubAddressLower" IS '平台 Hub 小写地址。';
COMMENT ON COLUMN "platform_contract_deployments"."deploymentTxHash" IS '部署交易哈希。';
COMMENT ON COLUMN "platform_contract_deployments"."activeFromBlock" IS '生效区块高度。';
COMMENT ON COLUMN "platform_contract_deployments"."createdAt" IS '创建时间。';
COMMENT ON COLUMN "platform_contract_deployments"."updatedAt" IS '更新时间。';

COMMENT ON TABLE "creator_releases" IS '创作者发行草稿与发布流程记录。';
COMMENT ON COLUMN "creator_releases"."id" IS '发行记录 ID。';
COMMENT ON COLUMN "creator_releases"."creatorUserId" IS '创作者用户 ID。';
COMMENT ON COLUMN "creator_releases"."title" IS '发行标题。';
COMMENT ON COLUMN "creator_releases"."artistName" IS '艺人名称。';
COMMENT ON COLUMN "creator_releases"."albumName" IS '专辑名称。';
COMMENT ON COLUMN "creator_releases"."genreLabel" IS '风格标签。';
COMMENT ON COLUMN "creator_releases"."slug" IS '访问 slug。';
COMMENT ON COLUMN "creator_releases"."description" IS '发行描述。';
COMMENT ON COLUMN "creator_releases"."status" IS '工作流状态。';
COMMENT ON COLUMN "creator_releases"."currentStage" IS '当前编辑阶段。';
COMMENT ON COLUMN "creator_releases"."accessModel" IS '访问模式。';
COMMENT ON COLUMN "creator_releases"."previewSeconds" IS '试听秒数。';
COMMENT ON COLUMN "creator_releases"."priceEth" IS 'ETH 价格字符串。';
COMMENT ON COLUMN "creator_releases"."royaltyBps" IS '版税基点。';
COMMENT ON COLUMN "creator_releases"."audioSourceName" IS '本地音频源文件名。';
COMMENT ON COLUMN "creator_releases"."coverSourceName" IS '本地封面源文件名。';
COMMENT ON COLUMN "creator_releases"."audioStorageObjectId" IS '音频内容对象 ID。';
COMMENT ON COLUMN "creator_releases"."coverStorageObjectId" IS '封面内容对象 ID。';
COMMENT ON COLUMN "creator_releases"."metadataStorageObjectId" IS 'metadata 内容对象 ID。';
COMMENT ON COLUMN "creator_releases"."platformDeploymentId" IS '发布使用的平台部署 ID。';
COMMENT ON COLUMN "creator_releases"."splitterAddress" IS '分账实例合约地址。';
COMMENT ON COLUMN "creator_releases"."publishTxHash" IS '发布交易哈希。';
COMMENT ON COLUMN "creator_releases"."publishBlockNumber" IS '发布区块高度。';
COMMENT ON COLUMN "creator_releases"."tokenId" IS '链上 token ID。';
COMMENT ON COLUMN "creator_releases"."metadataDocument" IS '完整 metadata JSON。';
COMMENT ON COLUMN "creator_releases"."royaltySplits" IS '版税分账配置。';
COMMENT ON COLUMN "creator_releases"."publishedResourceId" IS '对应资源索引 ID。';
COMMENT ON COLUMN "creator_releases"."activityLog" IS '最近流程活动日志。';
COMMENT ON COLUMN "creator_releases"."statusMessage" IS '短状态消息。';
COMMENT ON COLUMN "creator_releases"."latestError" IS '最近错误详情。';
COMMENT ON COLUMN "creator_releases"."publishedAt" IS '首次发布成功时间。';
COMMENT ON COLUMN "creator_releases"."lastActivityAt" IS '最近业务活动时间。';
COMMENT ON COLUMN "creator_releases"."createdAt" IS '创建时间。';
COMMENT ON COLUMN "creator_releases"."updatedAt" IS '更新时间。';

COMMENT ON TABLE "resources" IS '可评论的资源索引。';
COMMENT ON COLUMN "resources"."id" IS '资源记录 ID。';
COMMENT ON COLUMN "resources"."resourceKey" IS '稳定资源键。';
COMMENT ON COLUMN "resources"."type" IS '资源类型。';
COMMENT ON COLUMN "resources"."platformDeploymentId" IS '平台部署 ID。';
COMMENT ON COLUMN "resources"."chainId" IS '链 ID。';
COMMENT ON COLUMN "resources"."contractAddress" IS '合约地址。';
COMMENT ON COLUMN "resources"."contractAddressLower" IS '小写合约地址。';
COMMENT ON COLUMN "resources"."tokenId" IS 'token ID。';
COMMENT ON COLUMN "resources"."contentCid" IS '内容 CID。';
COMMENT ON COLUMN "resources"."title" IS '资源标题。';
COMMENT ON COLUMN "resources"."ownerUserId" IS '资源归属用户 ID。';
COMMENT ON COLUMN "resources"."createdAt" IS '创建时间。';
COMMENT ON COLUMN "resources"."updatedAt" IS '更新时间。';

COMMENT ON TABLE "purchases" IS '发行购买交易记录。';
COMMENT ON COLUMN "purchases"."id" IS '购买记录 ID。';
COMMENT ON COLUMN "purchases"."releaseId" IS '发行 ID。';
COMMENT ON COLUMN "purchases"."buyerUserId" IS '购买用户 ID。';
COMMENT ON COLUMN "purchases"."walletAddress" IS '购买钱包地址。';
COMMENT ON COLUMN "purchases"."walletAddressLower" IS '购买钱包小写地址。';
COMMENT ON COLUMN "purchases"."chainId" IS '购买链 ID。';
COMMENT ON COLUMN "purchases"."txHash" IS '购买交易哈希。';
COMMENT ON COLUMN "purchases"."txHashLower" IS '购买交易小写哈希。';
COMMENT ON COLUMN "purchases"."amountWei" IS '支付金额（wei 字符串）。';
COMMENT ON COLUMN "purchases"."status" IS '购买状态。';
COMMENT ON COLUMN "purchases"."purchasedAt" IS '链上确认时间。';
COMMENT ON COLUMN "purchases"."createdAt" IS '创建时间。';
COMMENT ON COLUMN "purchases"."updatedAt" IS '更新时间。';

COMMENT ON TABLE "comments" IS '资源评论。';
COMMENT ON COLUMN "comments"."id" IS '评论 ID。';
COMMENT ON COLUMN "comments"."resourceId" IS '资源 ID。';
COMMENT ON COLUMN "comments"."userId" IS '评论用户 ID。';
COMMENT ON COLUMN "comments"."parentId" IS '父评论 ID。';
COMMENT ON COLUMN "comments"."body" IS '评论正文。';
COMMENT ON COLUMN "comments"."status" IS '评论状态。';
COMMENT ON COLUMN "comments"."createdAt" IS '创建时间。';
COMMENT ON COLUMN "comments"."updatedAt" IS '更新时间。';
COMMENT ON COLUMN "comments"."deletedAt" IS '软删除时间。';

COMMENT ON TABLE "comment_reactions" IS '评论反应记录。';
COMMENT ON COLUMN "comment_reactions"."id" IS '反应记录 ID。';
COMMENT ON COLUMN "comment_reactions"."commentId" IS '评论 ID。';
COMMENT ON COLUMN "comment_reactions"."userId" IS '用户 ID。';
COMMENT ON COLUMN "comment_reactions"."reactionType" IS '反应类型。';
COMMENT ON COLUMN "comment_reactions"."createdAt" IS '创建时间。';

COMMENT ON TABLE "comment_reports" IS '评论举报记录。';
COMMENT ON COLUMN "comment_reports"."id" IS '举报记录 ID。';
COMMENT ON COLUMN "comment_reports"."commentId" IS '被举报评论 ID。';
COMMENT ON COLUMN "comment_reports"."reporterUserId" IS '举报人用户 ID。';
COMMENT ON COLUMN "comment_reports"."reason" IS '举报原因。';
COMMENT ON COLUMN "comment_reports"."details" IS '补充说明。';
COMMENT ON COLUMN "comment_reports"."status" IS '处理状态。';
COMMENT ON COLUMN "comment_reports"."createdAt" IS '创建时间。';
COMMENT ON COLUMN "comment_reports"."updatedAt" IS '更新时间。';

COMMENT ON TABLE "comment_moderation_logs" IS '评论审核审计日志。';
COMMENT ON COLUMN "comment_moderation_logs"."id" IS '审核日志 ID。';
COMMENT ON COLUMN "comment_moderation_logs"."commentId" IS '评论 ID。';
COMMENT ON COLUMN "comment_moderation_logs"."moderatorUserId" IS '审核用户 ID。';
COMMENT ON COLUMN "comment_moderation_logs"."action" IS '审核动作。';
COMMENT ON COLUMN "comment_moderation_logs"."note" IS '审核备注。';
COMMENT ON COLUMN "comment_moderation_logs"."createdAt" IS '创建时间。';
