import React, { useState, useEffect } from 'react';
import { DollarSign, Upload, ShieldCheck, Music2 } from 'lucide-react';
import { ethers } from 'ethers';

declare global {
  interface Window {
    ethereum?: any;
  }
}

// Assume these ABIs would be generated by hardhat
const MUSIC_ASSET_ABI = [
  "function mintTrack(address artist, string calldata tokenURI, address royaltyReceiver, uint96 feeNumerator) public returns (uint256)",
  "function tokenURI(uint256 tokenId) public view returns (string)"
];

const ROYALTY_SPLITTER_FACTORY_ABI = [
  "function createSplitter(address[] memory payees, uint256[] memory shares) public returns (address)"
];

const PLATFORM_HUB_ABI = [
  "function tipTrack(uint256 tokenId) public payable",
  "function buyAccess(uint256 tokenId) public payable",
  "function checkAccess(address user, uint256 tokenId) public view returns (bool)"
];

// Address placeholders (to be updated on deploy)
const MUSIC_ASSET_ADDRESS = "0x0000000000000000000000000000000000000000";
const FACTORY_ADDRESS = "0x0000000000000000000000000000000000000000";
const HUB_ADDRESS = "0x0000000000000000000000000000000000000000";

export default function MusicPlatform() {
  const [provider, setProvider] = useState<ethers.BrowserProvider | null>(null);
  const [signer, setSigner] = useState<ethers.JsonRpcSigner | null>(null);
  const [account, setAccount] = useState<string>('');
  const [status, setStatus] = useState<string>('');

  // Forms
  const [uploadURI, setUploadURI] = useState('');
  const [tipTokenId, setTipTokenId] = useState('');
  const [tipAmount, setTipAmount] = useState('');

  useEffect(() => {
    if (window.ethereum) {
      const web3Provider = new ethers.BrowserProvider(window.ethereum);
      setProvider(web3Provider);
    }
  }, []);

  const connectWallet = async () => {
    if (!provider) return alert("Please install MetaMask!");
    try {
      const userSigner = await provider.getSigner();
      setSigner(userSigner);
      setAccount(await userSigner.getAddress());
      setStatus("Connected to Web3 Auth Layer \u2705");
    } catch (e) {
      console.error(e);
      setStatus("Failed to connect");
    }
  };

  const handlePublish = async () => {
    if (!signer) return alert("Connect wallet first");
    try {
      setStatus("Creating Splityter...");
      const factory = new ethers.Contract(FACTORY_ADDRESS, ROYALTY_SPLITTER_FACTORY_ABI, signer);
      
      // Setup simple 100% to self for demo
      const tx1 = await factory.createSplitter([account], [100]);
      await tx1.wait();
      setStatus("Splitter Created! Minting NFT...");
      
      // Let's pretend the created splitter is at this mock address from event
      const mockSplitterAddress = account;

      const musicAsset = new ethers.Contract(MUSIC_ASSET_ADDRESS, MUSIC_ASSET_ABI, signer);
      const tx2 = await musicAsset.mintTrack(
        account,
        uploadURI || "ipfs://bafyre...", 
        mockSplitterAddress,
        1000 // 10% royalty
      );
      await tx2.wait();
      setStatus("Music Minted and Anchor Established \u2705");
    } catch (e: any) {
      setStatus("Publish Failed: " + (e.message || "Error"));
    }
  };

  const handleTip = async () => {
    if (!signer) return alert("Connect wallet first");
    try {
      setStatus("Tipping...");
      const hub = new ethers.Contract(HUB_ADDRESS, PLATFORM_HUB_ABI, signer);
      const val = ethers.parseEther(tipAmount || "0.01");
      const tx = await hub.tipTrack(tipTokenId || "0", { value: val });
      await tx.wait();
      setStatus(`Tipped ${tipAmount || "0.01"} ETH Successfully! \u2705`);
    } catch (e: any) {
      setStatus("Tip Failed");
    }
  };

  return (
    <div className="min-h-screen bg-neutral-950 text-white font-sans selection:bg-pink-500/30">
      <div className="max-w-6xl mx-auto px-6 py-12">
        <header className="flex items-center justify-between mb-16">
          <div className="flex items-center space-x-3">
            <div className="p-3 bg-gradient-to-br from-purple-500 to-pink-500 rounded-2xl shadow-lg shadow-pink-500/20">
              <Music2 className="w-8 h-8 text-white" />
            </div>
            <h1 className="text-3xl font-extrabold bg-clip-text text-transparent bg-gradient-to-r from-purple-400 to-pink-400 tracking-tight">
              FreeFlow Web3
            </h1>
          </div>
          <button 
            onClick={connectWallet}
            className="px-6 py-2.5 rounded-full bg-white/5 border border-white/10 hover:bg-white/10 transition-all font-medium flex items-center space-x-2 backdrop-blur-md"
          >
            <ShieldCheck className="w-4 h-4 text-emerald-400" />
            <span>{account ? `${account.slice(0, 6)}...${account.slice(-4)}` : "Connect Wallet"}</span>
          </button>
        </header>

        {status && (
          <div className="mb-8 p-4 rounded-xl bg-indigo-500/10 border border-indigo-500/20 text-indigo-300 text-sm font-medium animate-pulse">
            System Message: {status}
          </div>
        )}

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {/* Minting Panel */}
          <div className="bg-white/[0.02] border border-white/5 rounded-3xl p-8 backdrop-blur-2xl hover:border-pink-500/30 transition-all group">
            <div className="w-12 h-12 bg-pink-500/10 rounded-2xl flex items-center justify-center mb-6 text-pink-400 group-hover:scale-110 transition-transform">
              <Upload className="w-6 h-6" />
            </div>
            <h2 className="text-2xl font-bold mb-2">Publish Track</h2>
            <p className="text-neutral-400 text-sm mb-8">Anchor your music to the blockchain with an automated royalty splitter.</p>
            
            <div className="space-y-4">
              <div>
                <label className="block text-xs font-semibold text-neutral-500 uppercase tracking-wider mb-2">IPFS CID/URI</label>
                <input 
                  type="text"
                  value={uploadURI}
                  onChange={(e) => setUploadURI(e.target.value)}
                  placeholder="ipfs://..."
                  className="w-full bg-black/50 border border-white/10 rounded-xl px-4 py-3 focus:outline-none focus:border-pink-500 focus:ring-1 focus:ring-pink-500 transition-all"
                />
              </div>
              <button 
                onClick={handlePublish}
                className="w-full py-4 rounded-xl bg-gradient-to-r from-purple-500 to-pink-500 hover:opacity-90 font-bold shadow-lg shadow-pink-500/25 transition-all active:scale-[0.98]"
              >
                Mint & Create Splitter
              </button>
            </div>
          </div>

          {/* Tipping Panel */}
          <div className="bg-white/[0.02] border border-white/5 rounded-3xl p-8 backdrop-blur-2xl hover:border-emerald-500/30 transition-all group">
            <div className="w-12 h-12 bg-emerald-500/10 rounded-2xl flex items-center justify-center mb-6 text-emerald-400 group-hover:scale-110 transition-transform">
              <DollarSign className="w-6 h-6" />
            </div>
            <h2 className="text-2xl font-bold mb-2">Direct Tip / Access</h2>
            <p className="text-neutral-400 text-sm mb-8">Send funds directly to the track's royalty pool via the Platform Hub.</p>

            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-semibold text-neutral-500 uppercase tracking-wider mb-2">Track ID</label>
                  <input 
                    type="text"
                    value={tipTokenId}
                    onChange={(e) => setTipTokenId(e.target.value)}
                    placeholder="e.g. 0"
                    className="w-full bg-black/50 border border-white/10 rounded-xl px-4 py-3 focus:outline-none focus:border-emerald-500 transition-all"
                  />
                </div>
                <div>
                  <label className="block text-xs font-semibold text-neutral-500 uppercase tracking-wider mb-2">Amount (ETH)</label>
                  <input 
                    type="text"
                    value={tipAmount}
                    onChange={(e) => setTipAmount(e.target.value)}
                    placeholder="0.01"
                    className="w-full bg-black/50 border border-white/10 rounded-xl px-4 py-3 focus:outline-none focus:border-emerald-500 transition-all"
                  />
                </div>
              </div>
              <button 
                onClick={handleTip}
                className="w-full py-4 rounded-xl bg-gradient-to-r from-emerald-500 to-teal-500 hover:opacity-90 font-bold shadow-lg shadow-emerald-500/25 transition-all active:scale-[0.98]"
              >
                Send Tip
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
