COMMENT ON TYPE "CommentStatus" IS '评论的审核和可见状态：PUBLISHED 正常展示，HIDDEN 审核隐藏，DELETED 软删除。';
COMMENT ON TYPE "ResourceType" IS '可被评论、归属或索引的业务资源类型：TRACK 单曲，ALBUM 专辑，POST 创作者动态或文章。';
COMMENT ON TYPE "CreatorReleaseStatus" IS '创作者发行从草稿到链上发布的工作流状态。';

COMMENT ON TABLE "users" IS '应用用户，一个用户可以绑定多个已验证钱包身份。';
COMMENT ON COLUMN "users"."id" IS '应用内部用户 ID。';
COMMENT ON COLUMN "users"."displayName" IS '用户公开展示名称。';
COMMENT ON COLUMN "users"."avatarUrl" IS '用户头像地址。';
COMMENT ON COLUMN "users"."primaryWalletAddress" IS '当前主钱包地址，保留用户侧校验和大小写。';
COMMENT ON COLUMN "users"."createdAt" IS '用户记录创建时间。';
COMMENT ON COLUMN "users"."updatedAt" IS '用户记录最后更新时间。';

COMMENT ON TABLE "wallet_identities" IS '已验证钱包身份，同一链上的同一地址只能归属一个用户。';
COMMENT ON COLUMN "wallet_identities"."id" IS '钱包身份记录 ID。';
COMMENT ON COLUMN "wallet_identities"."userId" IS '归属的应用用户 ID。';
COMMENT ON COLUMN "wallet_identities"."address" IS '钱包地址，保留用户侧校验和大小写。';
COMMENT ON COLUMN "wallet_identities"."addressLower" IS '小写钱包地址，用于唯一约束和查询。';
COMMENT ON COLUMN "wallet_identities"."chainId" IS '钱包验证时所在的 EVM 链 ID。';
COMMENT ON COLUMN "wallet_identities"."isPrimary" IS '是否为用户当前主钱包。';
COMMENT ON COLUMN "wallet_identities"."verifiedAt" IS '钱包首次验证时间。';
COMMENT ON COLUMN "wallet_identities"."lastAuthenticatedAt" IS '钱包最近一次完成认证的时间。';
COMMENT ON COLUMN "wallet_identities"."createdAt" IS '钱包身份记录创建时间。';
COMMENT ON COLUMN "wallet_identities"."updatedAt" IS '钱包身份记录最后更新时间。';

COMMENT ON TABLE "siwe_nonces" IS 'SIWE 登录一次性 nonce，数据库只保存哈希以降低重放风险。';
COMMENT ON COLUMN "siwe_nonces"."id" IS 'nonce 记录 ID。';
COMMENT ON COLUMN "siwe_nonces"."nonceHash" IS '发给客户端 nonce 的 SHA-256 哈希。';
COMMENT ON COLUMN "siwe_nonces"."requestedAddress" IS '申请 nonce 时指定的钱包地址。';
COMMENT ON COLUMN "siwe_nonces"."requestedAddressLower" IS '小写的钱包地址，用于查询。';
COMMENT ON COLUMN "siwe_nonces"."requestedChainId" IS '申请 nonce 时指定的链 ID。';
COMMENT ON COLUMN "siwe_nonces"."expiresAt" IS 'nonce 过期时间。';
COMMENT ON COLUMN "siwe_nonces"."consumedAt" IS 'nonce 被成功消费的时间。';
COMMENT ON COLUMN "siwe_nonces"."createdAt" IS 'nonce 记录创建时间。';

COMMENT ON TABLE "auth_sessions" IS 'SIWE 验签成功后创建的服务端认证会话。';
COMMENT ON COLUMN "auth_sessions"."id" IS '会话记录 ID。';
COMMENT ON COLUMN "auth_sessions"."userId" IS '已认证的应用用户 ID。';
COMMENT ON COLUMN "auth_sessions"."walletIdentityId" IS '创建该会话的钱包身份 ID。';
COMMENT ON COLUMN "auth_sessions"."tokenHash" IS '客户端 Cookie 中不透明会话令牌的 SHA-256 哈希。';
COMMENT ON COLUMN "auth_sessions"."address" IS '验签时使用的钱包地址，保留原始大小写。';
COMMENT ON COLUMN "auth_sessions"."chainId" IS '验签时使用的 EVM 链 ID。';
COMMENT ON COLUMN "auth_sessions"."domain" IS '本次会话接受的 SIWE domain。';
COMMENT ON COLUMN "auth_sessions"."uri" IS '本次会话接受的 SIWE URI。';
COMMENT ON COLUMN "auth_sessions"."issuedAt" IS 'SIWE 消息声明的签发时间。';
COMMENT ON COLUMN "auth_sessions"."verifiedAt" IS '服务端验签成功时间。';
COMMENT ON COLUMN "auth_sessions"."expiresAt" IS '会话过期时间。';
COMMENT ON COLUMN "auth_sessions"."lastSeenAt" IS '中间件最近一次观察到该会话的时间。';
COMMENT ON COLUMN "auth_sessions"."revokedAt" IS '会话被撤销或过期维护任务标记的时间。';
COMMENT ON COLUMN "auth_sessions"."createdAt" IS '会话记录创建时间。';

COMMENT ON TABLE "storage_objects" IS '通过 Pinata 上传并在本地记录的文件对象。';
COMMENT ON COLUMN "storage_objects"."id" IS '存储对象记录 ID。';
COMMENT ON COLUMN "storage_objects"."uploaderUserId" IS '通过后端代理上传该对象的用户 ID。';
COMMENT ON COLUMN "storage_objects"."cid" IS 'Pinata 返回的 IPFS CID。';
COMMENT ON COLUMN "storage_objects"."pinataId" IS 'Pinata 服务侧文件 ID。';
COMMENT ON COLUMN "storage_objects"."name" IS '原始上传文件名。';
COMMENT ON COLUMN "storage_objects"."size" IS '文件大小，单位字节。';
COMMENT ON COLUMN "storage_objects"."mimeType" IS '上传文件的 MIME 类型。';
COMMENT ON COLUMN "storage_objects"."gatewayUrl" IS '当前用于访问 CID 的网关地址。';
COMMENT ON COLUMN "storage_objects"."network" IS 'Pinata 网络可见性，例如 public 或 private。';
COMMENT ON COLUMN "storage_objects"."groupId" IS '上传时使用的 Pinata group ID。';
COMMENT ON COLUMN "storage_objects"."createdAt" IS '上传记录创建时间。';

COMMENT ON TABLE "creator_releases" IS '创作者拥有的音乐发行草稿和链上发布流程记录。';
COMMENT ON COLUMN "creator_releases"."id" IS '发行记录 ID。';
COMMENT ON COLUMN "creator_releases"."creatorUserId" IS '拥有并编辑该发行的创作者用户 ID。';
COMMENT ON COLUMN "creator_releases"."title" IS '展示给创作者和听众的发行标题。';
COMMENT ON COLUMN "creator_releases"."artistName" IS '发行展示的艺人名称。';
COMMENT ON COLUMN "creator_releases"."albumName" IS '所属专辑名称。';
COMMENT ON COLUMN "creator_releases"."genreLabel" IS '创作者填写的风格或类型标签。';
COMMENT ON COLUMN "creator_releases"."slug" IS '创作者侧使用的草稿或访问 slug。';
COMMENT ON COLUMN "creator_releases"."description" IS '发行的长文本描述。';
COMMENT ON COLUMN "creator_releases"."status" IS '素材上传、元数据上传和发布流程状态。';
COMMENT ON COLUMN "creator_releases"."currentStage" IS '当前编辑步骤或前端工作流阶段。';
COMMENT ON COLUMN "creator_releases"."accessModel" IS '访问模式，目前由业务约束为 open 或 purchase。';
COMMENT ON COLUMN "creator_releases"."previewSeconds" IS '付费访问时允许试听的秒数。';
COMMENT ON COLUMN "creator_releases"."priceEth" IS 'ETH 价格，使用十进制字符串避免浮点精度问题。';
COMMENT ON COLUMN "creator_releases"."royaltyBps" IS '创作者版税比例，单位为基点。';
COMMENT ON COLUMN "creator_releases"."audioSourceName" IS '本地音频源文件名。';
COMMENT ON COLUMN "creator_releases"."audioSourcePath" IS '桌面端工作流记录的本地音频路径。';
COMMENT ON COLUMN "creator_releases"."coverSourceName" IS '本地封面源文件名。';
COMMENT ON COLUMN "creator_releases"."coverSourcePath" IS '桌面端工作流记录的本地封面路径。';
COMMENT ON COLUMN "creator_releases"."audioStorageObjectId" IS '关联的音频存储对象 ID，用于恢复上传文件详情和预览。';
COMMENT ON COLUMN "creator_releases"."coverStorageObjectId" IS '关联的封面存储对象 ID，用于恢复上传文件详情和预览。';
COMMENT ON COLUMN "creator_releases"."metadataStorageObjectId" IS '关联的 metadata 存储对象 ID，用于恢复上传文件详情和预览。';
COMMENT ON COLUMN "creator_releases"."splitterAddress" IS '该发行对应的版税分账合约地址。';
COMMENT ON COLUMN "creator_releases"."publishTxHash" IS '发布交易哈希。';
COMMENT ON COLUMN "creator_releases"."purchaseTxHash" IS '后端记录的购买交易哈希。';
COMMENT ON COLUMN "creator_releases"."tokenId" IS '链上铸造得到的 token ID。';
COMMENT ON COLUMN "creator_releases"."chainId" IS '发行所在的 EVM 链 ID。';
COMMENT ON COLUMN "creator_releases"."chainName" IS '客户端记录的人类可读链名称。';
COMMENT ON COLUMN "creator_releases"."explorerUrl" IS '发布交易或资产的区块浏览器地址。';
COMMENT ON COLUMN "creator_releases"."musicAssetAddress" IS '已发布音乐资产合约地址。';
COMMENT ON COLUMN "creator_releases"."royaltySplitterFactoryAddress" IS '发布时使用的版税分账工厂合约地址。';
COMMENT ON COLUMN "creator_releases"."platformHubAddress" IS '发布时使用的平台 Hub 合约地址。';
COMMENT ON COLUMN "creator_releases"."metadataDocument" IS '上传到 IPFS 的完整元数据 JSON。';
COMMENT ON COLUMN "creator_releases"."royaltySplits" IS '版税接收人及份额配置。';
COMMENT ON COLUMN "creator_releases"."activityLog" IS '最近的发行流程活动日志，业务层限制长度。';
COMMENT ON COLUMN "creator_releases"."statusMessage" IS '展示在创作者工作流中的短状态消息。';
COMMENT ON COLUMN "creator_releases"."latestError" IS '最近一次流程或发布错误详情。';
COMMENT ON COLUMN "creator_releases"."publishedAt" IS '首次进入 PUBLISHED 状态的时间。';
COMMENT ON COLUMN "creator_releases"."lastActivityAt" IS '最近一次有意义业务活动的时间。';
COMMENT ON COLUMN "creator_releases"."createdAt" IS '发行记录创建时间。';
COMMENT ON COLUMN "creator_releases"."updatedAt" IS '发行记录最后更新时间。';

COMMENT ON TABLE "resources" IS '可被评论的已发布资源，通常由已发布发行同步生成。';
COMMENT ON COLUMN "resources"."id" IS '资源记录 ID。';
COMMENT ON COLUMN "resources"."type" IS '资源业务类型。';
COMMENT ON COLUMN "resources"."chainId" IS '链上资源所在的 EVM 链 ID。';
COMMENT ON COLUMN "resources"."contractAddress" IS '合约地址，保留原始大小写。';
COMMENT ON COLUMN "resources"."contractAddressLower" IS '小写合约地址，用于唯一约束和查询。';
COMMENT ON COLUMN "resources"."tokenId" IS 'NFT 或链上资源的 token ID。';
COMMENT ON COLUMN "resources"."contentCid" IS '离线内容或元数据的主要 IPFS CID。';
COMMENT ON COLUMN "resources"."title" IS '资源在列表、资料页或评论区展示的标题。';
COMMENT ON COLUMN "resources"."ownerUserId" IS '当前后端可识别的资源拥有者用户 ID。';
COMMENT ON COLUMN "resources"."createdAt" IS '资源记录创建时间。';
COMMENT ON COLUMN "resources"."updatedAt" IS '资源记录最后更新时间。';

COMMENT ON TABLE "comments" IS '用户针对资源发表的讨论内容。';
COMMENT ON COLUMN "comments"."id" IS '评论记录 ID。';
COMMENT ON COLUMN "comments"."resourceId" IS '被评论的资源 ID。';
COMMENT ON COLUMN "comments"."userId" IS '评论作者用户 ID。';
COMMENT ON COLUMN "comments"."parentId" IS '父级评论 ID，用于楼中楼回复。';
COMMENT ON COLUMN "comments"."body" IS '评论正文。';
COMMENT ON COLUMN "comments"."status" IS '评论审核和可见状态。';
COMMENT ON COLUMN "comments"."createdAt" IS '评论创建时间。';
COMMENT ON COLUMN "comments"."updatedAt" IS '评论最后编辑或审核更新时间。';
COMMENT ON COLUMN "comments"."deletedAt" IS '评论软删除时间。';

COMMENT ON TABLE "comment_reactions" IS '某个用户对某条评论的一次反应。';
COMMENT ON COLUMN "comment_reactions"."id" IS '评论反应记录 ID。';
COMMENT ON COLUMN "comment_reactions"."commentId" IS '被反应的评论 ID。';
COMMENT ON COLUMN "comment_reactions"."userId" IS '产生反应的用户 ID。';
COMMENT ON COLUMN "comment_reactions"."reactionType" IS '反应类型，由应用层控制枚举或表情代码。';
COMMENT ON COLUMN "comment_reactions"."createdAt" IS '反应创建时间。';

COMMENT ON TABLE "comment_reports" IS '用户针对评论提交的审核举报。';
COMMENT ON COLUMN "comment_reports"."id" IS '举报记录 ID。';
COMMENT ON COLUMN "comment_reports"."commentId" IS '被举报的评论 ID。';
COMMENT ON COLUMN "comment_reports"."reporterUserId" IS '提交举报的用户 ID。';
COMMENT ON COLUMN "comment_reports"."reason" IS '机器可读的举报原因。';
COMMENT ON COLUMN "comment_reports"."details" IS '用户填写的补充举报说明。';
COMMENT ON COLUMN "comment_reports"."status" IS '举报处理状态，目前由应用层控制。';
COMMENT ON COLUMN "comment_reports"."createdAt" IS '举报创建时间。';
COMMENT ON COLUMN "comment_reports"."updatedAt" IS '举报最后更新时间。';

COMMENT ON TABLE "comment_moderation_logs" IS '针对评论执行审核动作的审计日志。';
COMMENT ON COLUMN "comment_moderation_logs"."id" IS '审核日志记录 ID。';
COMMENT ON COLUMN "comment_moderation_logs"."commentId" IS '被审核的评论 ID。';
COMMENT ON COLUMN "comment_moderation_logs"."moderatorUserId" IS '执行审核的用户 ID，系统任务产生时为空。';
COMMENT ON COLUMN "comment_moderation_logs"."action" IS '机器可读的审核动作。';
COMMENT ON COLUMN "comment_moderation_logs"."note" IS '审核备注。';
COMMENT ON COLUMN "comment_moderation_logs"."createdAt" IS '审核动作记录时间。';
