/**
 * Inversify 注入标识符统一管理
 */
export const DISymbol = {
  Store: Symbol.for('Store'),
  Sequelize: Symbol.for('Sequelize'),
  FileCacheManager: Symbol.for('FileCacheManager'),
  WindowManager: Symbol.for('WindowManager'),
  HifiniDownloader: Symbol.for('HifiniDownloader'),
  ProxyServerManager: Symbol.for('ProxyServerManager'),
  LocalLibraryService: Symbol.for('LocalLibraryService'),
  TrackService: Symbol.for('TrackService'),
  PlaylistService: Symbol.for('PlaylistService'),
  LyricService: Symbol.for('LyricService'),
  HifiniMusic: Symbol.for('HifiniMusic'),
  NetEaseCloudMusic: Symbol.for('NetEaseCloudMusic'),
  QQMusic: Symbol.for('QQMusic'),
  PlaylistDetailDataSource: Symbol.for('PlaylistDetailDataSource'),
  HifiniThreadCacheDataSource: Symbol.for('HifiniThreadCacheDataSource'),
  PlaylistDataSource: Symbol.for('PlaylistDataSource'),
  TrackDataSource: Symbol.for('TrackDataSource'),
  TrackRepository: Symbol.for('TrackRepository'),
  PlaylistRepository: Symbol.for('PlaylistRepository'),
  HifiniThreadCacheRepository: Symbol.for('HifiniThreadCacheRepository'),
  PreferenceService: Symbol.for('PreferenceService'),
  IpcController: Symbol.for('IpcController'),
  TrayManager: Symbol.for('TrayManager'),
  ShortcutManager: Symbol.for('ShortcutManager'),
  SessionDataSource: Symbol.for('SessionDataSource'),
  RunningOS: Symbol.for('RunningOS'),
  IsDevelopment: Symbol.for('IsDevelopment'),
  DataPath: Symbol.for('DataPath'),
  Bilibili: Symbol.for('Bilibili'),
  BilibiliService: Symbol.for('BilibiliService'),
  SettingsStore: Symbol.for('SettingsStore'),
  ConfigService: Symbol.for('ConfigService'),
};