/**
 * Inversify 注入标识符统一管理
 */
export const DISymbol = {
  Logger: Symbol.for('Logger'),
  Store: Symbol.for('Store'),
  Sequelize: Symbol.for('Sequelize'),
  FileCacheManager: Symbol.for('FileCacheManager'),
  WindowManager: Symbol.for('WindowManager'),
  HifiniDownloader: Symbol.for('HifiniDownloader'),
  ProxyServerManager: Symbol.for('ProxyServerManager'),
  LocalLibraryService: Symbol.for('LocalLibraryService'),
  TrackService: Symbol.for('TrackService'),
  PlaylistService: Symbol.for('PlaylistService'),
  LyricService: Symbol.for('LyricService'),
  HifiniMusic: Symbol.for('HifiniMusic'),
  NetEaseCloudMusic: Symbol.for('NetEaseCloudMusic'),
  QQMusic: Symbol.for('QQMusic'),
  YouTubeMusic: Symbol.for('YouTubeMusic'),
  YouTube: Symbol.for('YouTube'),
  FreeFlowProvider: Symbol.for('FreeFlowProvider'),
  TrackRepository: Symbol.for('TrackRepository'),
  PlaylistRepository: Symbol.for('PlaylistRepository'),
  HifiniThreadCacheRepository: Symbol.for('HifiniThreadCacheRepository'),
  PreferenceService: Symbol.for('PreferenceService'),
  IpcController: Symbol.for('IpcController'),
  TrayManager: Symbol.for('TrayManager'),
  ShortcutManager: Symbol.for('ShortcutManager'),
  RunningOS: Symbol.for('RunningOS'),
  IsDevelopment: Symbol.for('IsDevelopment'),
  DataPath: Symbol.for('DataPath'),
  Bilibili: Symbol.for('Bilibili'),
  BilibiliService: Symbol.for('BilibiliService'),
  SettingsStore: Symbol.for('SettingsStore'),
  ConfigService: Symbol.for('ConfigService'),
  AiTextService: Symbol.for('AiTextService'),
  ProviderManager: Symbol.for('ProviderManager'),
  SearchService: Symbol.for('SearchService'),
};
